#!/bin/bash

echo ""
echo "  ╔══════════════════════════════════════════════════════╗"
echo "  ║       Linux Fundamentals Workshop — IEEE uOttawa     ║"
echo "  ╠══════════════════════════════════════════════════════╣"
echo "  ║                                                      ║"
echo "  ║  27 challenges across 9 Linux concepts.              ║"
echo "  ║  Complete each task and run 'verify' to get flags.   ║"
echo "  ║                                                      ║"
echo "  ║  Commands:                                           ║"
echo "  ║    challenges     View the full challenge list       ║"
echo "  ║    verify X.Y     Check your work on a challenge     ║"
echo "  ║    reset X.Y      Reset a challenge to try again     ║"
echo "  ║    status         Show overall progress              ║"
echo "  ║    welcome        Show this message again            ║"
echo "  ║                                                      ║"
echo "  ║  Type 'challenges' to get started!                   ║"
echo "  ║                                                      ║"
echo "  ╚══════════════════════════════════════════════════════╝"
echo ""
